import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next.js and must not be edited
  { ignores: [".next/**", "node_modules/**", "public/**", "storage/**", "coverage/**", "next-env.d.ts"] },
];

export default config;
