import { site } from "@/lib/site";
import type { PageContent } from "./types";

export type LocationKey = "dubai" | "abudhabi" | "sharjah" | "ajman" | "rak" | "fujairah" | "uaq";

/** Location pages — each with location-specific content (client rule: no duplicated location pages). */
export const locationsEn: Record<LocationKey, PageContent> = {
  dubai: {
    // Old site title/description kept as-is (page ranks on Google) — see docs/legacy-seo.json
    metaTitle: "Snagging Companies in Dubai | Professional Property Inspections",
    metaTitleAbsolute: true,
    metaDescription: "Are you looking for certified snagging services in Dubai? We inspect villas, apartments & commercial properties and deliver detailed reports. Book Now!!",
    breadcrumb: "Snagging in Dubai",
    navLabel: "Dubai",
    summary: "Our home base — fastest scheduling for handovers across Dubai.",
    h1: "Property snagging services in Dubai",
    intro: "Dubai sees thousands of off-plan handovers every year, and developers give buyers a short window to report defects. From our Business Bay office we reach most communities the same day.",
    schema: "service",
    city: "Dubai",
    communities: ["Dubai Hills Estate", "Business Bay", "Downtown Dubai", "Dubai Marina & JBR", "Jumeirah Village Circle (JVC)", "Dubai Creek Harbour", "Arabian Ranches", "Damac Hills", "Dubai South", "Meydan & MBR City"],
    sections: [
      { title: "Snagging for Dubai handovers", paragraphs: ["Handover peaks can fill inspection calendars weeks ahead. Book as soon as your handover notice arrives so your report reaches the developer in time."] },
      { title: "What we see most in Dubai new builds", bullets: ["Finishing defects in fast-tracked apartment towers", "Balcony door seals and window alignment", "AC units under-performing in summer", "Bathroom silicone, grout and drainage issues"] },
    ],
    faqs: [
      { q: "How quickly can you inspect in Dubai?", a: "We usually schedule Dubai inspections within a few days, and reports are delivered within 6 to 24 hours." },
      { q: "Do you cover all Dubai communities?", a: "Yes — from Dubai Marina to Dubai South and everything in between." },
    ],
    related: ["apartmentSnagging", "villaSnagging", "handoverInspection", "dlpInspection"],
  },
  abudhabi: {
    // Old site title/description kept as-is (page ranks on Google) — see docs/legacy-seo.json
    metaTitle: "Best Property Snagging Abu Dhabi | Professional Inspections UAE",
    metaTitleAbsolute: true,
    metaDescription: "Expert property snagging services in Abu Dhabi & UAE. Get detailed inspection reports before handover to find defects and protect your investment. Book now",
    breadcrumb: "Snagging in Abu Dhabi",
    navLabel: "Abu Dhabi",
    summary: "Large villa communities on Yas, Saadiyat and Al Reem.",
    h1: "Property snagging services in Abu Dhabi",
    intro: "Abu Dhabi's newer communities are dominated by large villas and townhouses on master-planned islands. These homes have more outdoor area, more AC zones and more to check — so we plan Abu Dhabi inspections with extra time on site.",
    image: site.images.locations.abudhabi,
    schema: "service",
    city: "Abu Dhabi",
    communities: ["Yas Island", "Saadiyat Island", "Al Reem Island", "Al Raha Beach", "Al Reef", "Masdar City", "Al Shamkha", "Khalifa City"],
    sections: [
      { title: "Planning your Abu Dhabi inspection", paragraphs: ["Our engineers travel from Dubai, so we group Abu Dhabi bookings on set days. Tell us your handover date early and we will reserve a slot that leaves time to submit the report."] },
      { title: "Focus areas for Abu Dhabi villas", bullets: ["Roof and terrace waterproofing", "External works, gardens and drainage", "Multiple AC systems and water heaters", "Maid's and driver's room finishes"] },
    ],
    faqs: [{ q: "Is there an extra charge for Abu Dhabi?", a: "Contact us with your property details and location — we confirm the full price before booking." }],
    related: ["villaSnagging", "townhouseSnagging", "handoverInspection", "thermalImaging"],
  },
  sharjah: {
    // Old site title/description kept as-is (page ranks on Google) — see docs/legacy-seo.json
    metaTitle: "Expert Property Snagging Sharjah | Inspection Services UAE",
    metaTitleAbsolute: true,
    metaDescription: "Professional property snagging services in Sharjah, UAE. Get detailed inspection reports to spot defects before handover and protect your investment. Book now",
    breadcrumb: "Snagging in Sharjah",
    navLabel: "Sharjah",
    summary: "Fast-growing new communities and resale apartments.",
    h1: "Property snagging services in Sharjah",
    intro: "Sharjah's new master communities have brought a wave of first-time handovers, alongside a large stock of older apartment buildings. We inspect both — new-build snagging and condition checks for resale homes.",
    image: site.images.locations.sharjah,
    schema: "service",
    city: "Sharjah",
    communities: ["Aljada", "Tilal City", "Al Zahia", "Muwaileh", "Al Mamsha", "Sharjah Waterfront City", "Al Khan", "Al Majaz"],
    sections: [
      { title: "New communities", paragraphs: ["For new handovers we run full snagging and help you prepare the report for the developer's customer care team."] },
      { title: "Older buildings", paragraphs: ["For resale and rental apartments in established areas, a secondary property inspection focuses on AC age, plumbing, electrical safety and signs of past leaks."] },
    ],
    faqs: [{ q: "Do you inspect older apartments in Sharjah?", a: "Yes. Our secondary property inspection is designed for lived-in and older homes." }],
    related: ["apartmentSnagging", "secondaryInspection", "prePurchase", "handoverInspection"],
  },
  ajman: {
    metaTitle: "Property Snagging Ajman | Apartment & Villa Inspection",
    metaDescription: "Property snagging and inspection in Ajman for new apartments, villas and resale homes. Independent engineers, detailed photo reports and fast turnaround.",
    breadcrumb: "Snagging in Ajman",
    navLabel: "Ajman",
    summary: "New apartments and value-focused buyers.",
    h1: "Property snagging services in Ajman",
    intro: "Ajman attracts many first-time buyers and investors looking for value. On a tighter budget, it's even more important that repairs are paid by the developer, not by you — that's what a snagging report helps achieve.",
    schema: "service",
    city: "Ajman",
    communities: ["Al Zorah", "Emirates City", "Ajman Downtown", "Al Nuaimiya", "Al Rashidiya", "Al Yasmeen", "Al Helio"],
    sections: [
      { title: "Investors and landlords", paragraphs: ["If you're buying to rent, a snagging or pre-purchase inspection protects your yield: fewer repair call-outs and fewer tenant complaints in the first year."] },
      { title: "What we check", bullets: ["Finishes, tiles and joinery", "AC cooling and drainage", "Electrical points and DB panel", "Bathroom waterproofing indicators", "Balconies and windows"] },
    ],
    faqs: [{ q: "How do I book an inspection in Ajman?", a: "Send us your property type, location and preferred date through the quote form or WhatsApp, and we confirm a slot." }],
    related: ["apartmentSnagging", "prePurchase", "secondaryInspection", "sharjah"],
  },
  rak: {
    metaTitle: "Property Snagging Ras Al Khaimah | RAK Home Inspection",
    metaDescription: "Property snagging in Ras Al Khaimah for beachfront apartments and villas on Al Marjan Island, Mina Al Arab and Al Hamra. Coastal-focused checks and photo reports.",
    breadcrumb: "Snagging in Ras Al Khaimah",
    navLabel: "Ras Al Khaimah",
    summary: "Beachfront homes where humidity and salt air matter.",
    h1: "Property snagging services in Ras Al Khaimah",
    intro: "Many of RAK's new homes sit right on the coast. Sea air and high humidity are tough on metal fixings, window seals, external paint and AC outdoor units, so our RAK inspections pay extra attention to them.",
    schema: "service",
    city: "Ras Al Khaimah",
    communities: ["Al Marjan Island", "Mina Al Arab", "Al Hamra Village", "Julphar", "Al Nakheel", "Seih Al Uraibi"],
    sections: [
      { title: "Coastal checks we add", bullets: ["Corrosion on balcony railings and fixings", "Window and door seals against wind-driven rain", "External paint and render quality", "Condensation and mould risk in AC rooms", "Condition of outdoor AC units"] },
      { title: "Holiday homes and investors", paragraphs: ["Buying a holiday home or a short-let investment? We can inspect without you being present and send the report and photos digitally."] },
    ],
    faqs: [{ q: "Can you inspect if I live abroad?", a: "Yes. Arrange key access with the developer or your agent and we'll handle the inspection and send you the report." }],
    related: ["apartmentSnagging", "villaSnagging", "moistureDetection", "handoverInspection"],
  },
  fujairah: {
    metaTitle: "Property Snagging Fujairah | Home Inspection Fujairah",
    metaDescription: "Property snagging and inspection in Fujairah for new and resale homes on the east coast. Independent engineers and detailed photo reports.",
    breadcrumb: "Snagging in Fujairah",
    navLabel: "Fujairah",
    summary: "East-coast homes, inspected by appointment.",
    h1: "Property snagging services in Fujairah",
    intro: "Fujairah's east-coast location brings its own conditions — humidity from the sea and heavier rain events from the mountains than the west coast. Good waterproofing and drainage matter here.",
    schema: "service",
    city: "Fujairah",
    communities: ["Fujairah City", "Dibba Al Fujairah", "Al Aqah", "Kalba (nearby)"],
    sections: [
      { title: "Book ahead", paragraphs: ["We schedule Fujairah inspections by appointment. Share your handover or purchase date as early as possible so we can plan travel and still deliver your report in time."] },
      { title: "Focus areas", bullets: ["Roof, terrace and balcony drainage", "Waterproofing in wet areas", "Window and door seals", "AC performance and humidity control"] },
    ],
    faqs: [{ q: "Do you cover all of Fujairah?", a: "We cover Fujairah city and the wider emirate by appointment. Tell us your location when requesting a quote." }],
    related: ["moistureDetection", "villaSnagging", "prePurchase", "rak"],
  },
  uaq: {
    metaTitle: "Property Snagging Umm Al Quwain | UAQ Home Inspection",
    metaDescription: "Property snagging in Umm Al Quwain for new waterfront developments and resale homes. Engineer-led inspections and clear photo reports.",
    breadcrumb: "Snagging in Umm Al Quwain",
    navLabel: "Umm Al Quwain",
    summary: "Emerging waterfront communities and resale homes.",
    h1: "Property snagging services in Umm Al Quwain",
    intro: "Umm Al Quwain is seeing new waterfront and residential projects alongside its established neighbourhoods. Whether you're collecting keys to a new home or buying resale, an independent inspection tells you exactly what you're getting.",
    schema: "service",
    city: "Umm Al Quwain",
    communities: ["UAQ waterfront developments", "Al Salamah", "Al Raas", "Al Ramlah", "Umm Al Quwain city centre"],
    sections: [
      { title: "New handovers", paragraphs: ["For newly completed homes we run a full snagging inspection and prepare a report ready for the developer."] },
      { title: "Resale and older homes", paragraphs: ["For existing properties we focus on AC condition, plumbing, electrical safety, moisture and the quality of past repairs."] },
    ],
    faqs: [{ q: "How far in advance should I book in UAQ?", a: "Ideally one to two weeks before your handover or purchase deadline." }],
    related: ["handoverInspection", "secondaryInspection", "prePurchase", "ajman"],
  },
};
