import type { PageContent } from "./types";

type ServiceKey =
  | "snaggingServices" | "propertyInspection" | "villaSnagging" | "apartmentSnagging" | "townhouseSnagging"
  | "handoverInspection" | "preHandover" | "dlpInspection" | "elevenMonth" | "reInspection"
  | "prePurchase" | "secondaryInspection" | "thermalImaging" | "moistureDetection" | "hvacMep";

/**
 * Service pages — each one is written separately (client rule: no copy-paste pages with swapped keywords).
 * When editing, keep content specific to that service.
 */
export const servicesEn: Record<ServiceKey, PageContent> = {
  snaggingServices: {
    metaTitle: "Property Snagging Services in Dubai & UAE | All Inspections",
    metaDescription: "All our property snagging and inspection services in one place: handover, DLP, 11-month, pre-purchase, villa, apartment, thermal and MEP inspections across the UAE.",
    breadcrumb: "Services",
    navLabel: "All services",
    h1: "Property snagging and inspection services",
    intro: "Whether you are collecting keys from a developer, buying a resale home or approaching the end of your warranty, we have an inspection built for that moment.",
    schema: "service",
    sections: [
      { id: "handover", title: "New handover snagging", paragraphs: ["Find construction and finishing defects before you accept the property, while the developer is still responsible for fixing them at no cost to you."] },
      { id: "resale", title: "Resale and secondary market", paragraphs: ["A pre-purchase or secondary property inspection shows the real condition of a lived-in home, so you can negotiate, plan repairs or walk away with confidence."] },
      { id: "warranty", title: "During the defect liability period", paragraphs: ["DLP and 11-month inspections catch the defects that appear only after you move in — before the developer's obligation ends."] },
      { title: "Specialist inspections", bullets: ["Thermal imaging inspection", "Moisture detection", "HVAC and MEP inspection", "Building and asset condition audits", "Inspection for court and arbitration cases"] },
    ],
    related: ["handoverInspection", "dlpInspection", "prePurchase", "villaSnagging", "apartmentSnagging", "thermalImaging"],
  },
  propertyInspection: {
    metaTitle: "Property Inspection Dubai | Engineer-Led Home Inspections",
    metaDescription: "Independent property inspection in Dubai for apartments, villas and townhouses. Structure, MEP, HVAC and finishes checked, with a photo report in 6–24 hours.",
    breadcrumb: "Property inspection Dubai",
    navLabel: "Property inspection",
    summary: "A full condition check of any home — new, resale or rented.",
    h1: "Property inspection in Dubai",
    intro: "A property inspection is a full technical check of a home's condition. Unlike snagging, which focuses on new-build defects before handover, an inspection can be done on any property at any age.",
    schema: "service",
    includes: ["Civil and structural finishes", "Electrical panels, sockets and earthing", "Plumbing pressure, leaks and drainage", "AC performance and airflow", "Moisture readings in wet areas", "Doors, windows, balconies and terraces"],
    sections: [
      { title: "When a property inspection makes sense", bullets: ["You are buying a ready or resale property", "You are renting and want a move-in condition record", "You own a home and want to plan maintenance", "You suspect a leak, AC fault or electrical issue"] },
      { title: "What you receive", paragraphs: ["A structured report listing every finding with its location, a photograph, a severity rating and a recommendation, so you know what is urgent and what can wait."] },
    ],
    faqs: [
      { q: "What is the difference between snagging and a property inspection?", a: "Snagging is aimed at new properties before handover, so the developer fixes defects. A property inspection assesses the condition of any property, including older homes, to support buying, renting or maintenance decisions." },
      { q: "How long does a property inspection take?", a: "Most apartments take 2–3 hours and villas 3–5 hours, depending on size and condition." },
    ],
    related: ["prePurchase", "secondaryInspection", "thermalImaging", "dubai"],
  },
  villaSnagging: {
    metaTitle: "Villa Snagging Dubai | Detailed New Villa Inspection",
    metaDescription: "Villa snagging in Dubai covering roofs, terraces, external works, MEP, AC and every room. Engineer-led inspection with a photo report before handover.",
    breadcrumb: "Villa snagging Dubai",
    navLabel: "Villa snagging",
    summary: "Inside and out — roofs, terraces, gardens, MEP and every room.",
    h1: "Villa snagging in Dubai",
    intro: "Villas have far more to check than apartments: roofs, terraces, external walls, boundary walls, landscaping, drainage, multiple AC zones and often a maid's room and driver's room. Our villa snagging covers all of it.",
    schema: "service",
    includes: ["Roof waterproofing and slopes", "Terraces, balconies and railings", "External plaster, paint and boundary walls", "Garden drainage and irrigation points", "Every AC unit and thermostat", "Water heaters, pumps and tanks", "Kitchen, bathrooms and joinery", "Garage, gates and external lighting"],
    sections: [
      { title: "Why villas need a different approach", paragraphs: ["Many villa defects sit outside the living areas — ponding water on a roof, cracks in a boundary wall or poor falls on a terrace. These are expensive to fix later and easy to miss on a quick walk-through."] },
      { title: "How long it takes", paragraphs: ["A 3–4 bedroom villa usually takes 4–5 hours. Larger villas may need two engineers. You receive your report within 6–24 hours."] },
    ],
    faqs: [
      { q: "Do you check the roof of the villa?", a: "Yes. Where safe access exists, we check the roof waterproofing, slopes, drains and parapets, and use thermal imaging to spot moisture." },
      { q: "Can you inspect a villa before the developer's handover date?", a: "Yes. A pre-handover inspection is ideal for villas because it gives the developer more time to fix issues before you sign." },
    ],
    related: ["townhouseSnagging", "handoverInspection", "thermalImaging", "dubai"],
  },
  apartmentSnagging: {
    metaTitle: "Apartment Snagging Dubai | New Apartment Handover Inspection",
    metaDescription: "Apartment snagging in Dubai for studios to penthouses. We check finishes, MEP, AC, balcony, kitchen and bathrooms before you accept handover.",
    breadcrumb: "Apartment snagging Dubai",
    navLabel: "Apartment snagging",
    summary: "Studios to penthouses, checked room by room before handover.",
    h1: "Apartment snagging in Dubai",
    intro: "In an apartment, small defects add up: a misaligned door, a hollow tile, a weak AC or a slow drain. We check every room so your developer fixes them before you move in.",
    schema: "service",
    includes: ["Walls, ceilings and paint finish", "Floor tiles, skirting and grout", "Doors, windows and balcony sliders", "Kitchen cabinets, worktops and appliances", "Bathroom sanitaryware, silicone and drainage", "Electrical points and DB panel", "AC airflow and temperature", "Balcony waterproofing and railings"],
    sections: [
      { title: "Studio, 1, 2 and 3 bedroom apartments", paragraphs: ["Most apartments take 2–3 hours. We test every socket, tap, switch and AC unit, and photograph each defect with its exact location."] },
      { title: "Common apartment defects we find", bullets: ["Hollow or uneven floor tiles", "Gaps in bathroom silicone and grout", "Doors that rub or don't latch", "Balcony door seals that let in dust and water", "AC units that don't reach set temperature"] },
    ],
    faqs: [
      { q: "Is snagging worth it for a small apartment?", a: "Yes. Even studios regularly have dozens of defects. Getting them fixed under the developer's responsibility is far cheaper than repairing them later." },
      { q: "Do I need to be present during the inspection?", a: "It helps but isn't required. We can collect keys from the developer or your agent and send the report afterwards." },
    ],
    related: ["handoverInspection", "villaSnagging", "dlpInspection", "dubai"],
  },
  townhouseSnagging: {
    metaTitle: "Townhouse Snagging Dubai | New Townhouse Inspection",
    metaDescription: "Townhouse snagging in Dubai: shared walls, stairs, roof terraces, small gardens, MEP and finishes checked by engineers before you accept handover.",
    breadcrumb: "Townhouse snagging Dubai",
    navLabel: "Townhouse snagging",
    summary: "Multi-level homes with stairs, roof terraces and shared walls.",
    h1: "Townhouse snagging in Dubai",
    intro: "Townhouses combine villa features — gardens, roof terraces, several floors — with shared walls and compact layouts. That mix creates its own defects, from staircase finishes to water ingress at roof terraces.",
    schema: "service",
    includes: ["Staircase treads, handrails and balustrades", "Shared (party) walls for cracks and damp", "Roof terrace waterproofing and drainage", "Small garden levels and drainage", "AC units on each floor", "Kitchen, bathrooms and laundry"],
    sections: [
      { title: "What makes townhouses different", paragraphs: ["Each level has its own AC, wet areas and finishes, and roof terraces sit directly above bedrooms. We pay extra attention to waterproofing and to cracks along shared walls."] },
      { title: "Timing", paragraphs: ["A typical townhouse inspection takes 3–4 hours, with the report delivered within 6–24 hours."] },
    ],
    faqs: [{ q: "Do you check the roof terrace?", a: "Yes. We check falls, drains, waterproofing upstands and railings, and use moisture readings in the rooms below." }],
    related: ["villaSnagging", "handoverInspection", "moistureDetection", "dubai"],
  },
  handoverInspection: {
    metaTitle: "Handover Inspection Dubai | Snag Before You Sign",
    metaDescription: "Handover inspection in Dubai: we check your new property before you accept keys and give you a report to send to the developer. Book before your handover date.",
    breadcrumb: "Handover inspection Dubai",
    navLabel: "Handover inspection",
    summary: "Check the property before you sign the handover documents.",
    h1: "Handover inspection in Dubai",
    intro: "Your handover appointment is the moment of most leverage. Once you sign, it becomes harder to prove a defect was there from the start. A handover inspection gives you a documented list before you accept the keys.",
    schema: "service",
    includes: ["Full snagging of every room and system", "Photo evidence with exact locations", "Severity rating for each defect", "Report formatted for developer submission", "Advice on what to insist on before signing"],
    sections: [
      { title: "How a handover inspection works", bullets: ["You receive the handover notice from the developer", "We inspect on or before your appointment", "You submit our report to the developer", "The developer fixes the snags", "We re-inspect to confirm the fixes (optional)"] },
      { title: "When to book", paragraphs: ["As soon as you get the handover notice. Peak handover months fill up quickly, and booking early gives the developer time to fix issues before you move in."] },
    ],
    faqs: [
      { q: "Should I sign the handover if there are defects?", a: "Many developers let you sign with a snag list attached. Ask the developer to acknowledge our report in writing. If major issues exist, you can ask for them to be fixed before handover." },
      { q: "Can you attend the handover appointment with me?", a: "Yes, an engineer can join you to walk through the main issues with the developer's representative." },
    ],
    related: ["preHandover", "reInspection", "apartmentSnagging", "villaSnagging"],
  },
  preHandover: {
    metaTitle: "Pre-Handover Inspection | Snagging Before Completion",
    metaDescription: "Pre-handover inspection in the UAE: snag your property before the official handover so the developer has time to fix defects before you move in.",
    breadcrumb: "Pre-handover inspection",
    navLabel: "Pre-handover inspection",
    summary: "Inspect early so the developer fixes defects before handover day.",
    h1: "Pre-handover inspection",
    intro: "Some developers allow a buyer's inspection before the official handover appointment. Using that window means defects can be fixed before you sign, instead of after you move in.",
    schema: "service",
    includes: ["Full snagging of finishes and systems", "Priority list of defects to fix before handover", "Report you can share with the developer immediately", "Optional re-inspection before final handover"],
    sections: [
      { title: "Benefits of inspecting early", bullets: ["More time for the developer to fix issues", "Fewer repairs happening after you move in", "A stronger position at the handover meeting"] },
      { title: "How to arrange access", paragraphs: ["Ask your developer's handover team for a pre-handover or 'buyer's inspection' slot. We can coordinate directly with them on your behalf."] },
    ],
    faqs: [{ q: "Is a pre-handover inspection different from a handover inspection?", a: "The checks are the same; the timing differs. A pre-handover inspection happens earlier, leaving time for repairs before the handover appointment." }],
    related: ["handoverInspection", "reInspection", "developers", "dubai"],
  },
  dlpInspection: {
    metaTitle: "DLP Inspection Dubai | Defect Liability Period Inspection",
    metaDescription: "DLP inspection in Dubai: find defects that appear after move-in and report them while your developer is still responsible under the defect liability period.",
    breadcrumb: "DLP inspection",
    navLabel: "DLP inspection",
    summary: "Catch defects that appear after move-in, while the developer is liable.",
    h1: "DLP inspection (defect liability period)",
    intro: "After handover, developers remain responsible for fixing certain defects during the defect liability period (DLP). Some problems only appear once a home is lived in — leaks, cracks, AC faults — and a DLP inspection documents them while the developer still has to fix them.",
    schema: "service",
    includes: ["Re-check of earlier snags that may have returned", "New cracks, settlement and finishing failures", "Leaks and moisture in wet areas", "AC performance under real use", "Electrical faults and tripping circuits", "Report ready to submit to the developer"],
    sections: [
      { title: "How long is the DLP?", paragraphs: ["It is commonly 12 months for non-structural defects after handover, while structural liability lasts much longer. Always check the exact period in your sale and purchase agreement."] },
      { title: "When to book", paragraphs: ["Any time during the DLP if something looks wrong — and once more near the end of the period with an 11-month inspection."] },
    ],
    faqs: [
      { q: "What kind of defects appear during the DLP?", a: "Typical examples are hairline cracks, grout and silicone failures, slow leaks under sinks, AC drainage problems and doors that start to stick." },
      { q: "Do I need a DLP inspection if I had a handover snagging?", a: "Yes, ideally. Handover snagging finds what is visible on day one; a DLP inspection finds what develops with use." },
    ],
    related: ["elevenMonth", "moistureDetection", "hvacMep", "handoverInspection"],
  },
  elevenMonth: {
    metaTitle: "11-Month Inspection Dubai | Before Your Warranty Ends",
    metaDescription: "11-month inspection: a final snagging check just before your developer warranty expires, so every remaining defect is reported in time.",
    breadcrumb: "11-month inspection",
    navLabel: "11-month inspection",
    summary: "One last full check just before the developer's warranty runs out.",
    h1: "11-month inspection",
    intro: "The 11-month inspection is timed for the final weeks of a 12-month defect liability period. It is your last chance to report non-structural defects at the developer's expense.",
    schema: "service",
    includes: ["Full re-snagging of the property", "Status check of previously reported snags", "Defects that developed during the first year", "Clear list for submission before the deadline"],
    sections: [
      { title: "Why timing matters", paragraphs: ["Report too early and new issues may still appear; report after the DLP ends and repairs become your cost. Booking in month 10 or 11 leaves time for the developer to respond."] },
      { title: "Set a reminder", paragraphs: ["Note your handover date and book this inspection about 4–6 weeks before the first anniversary."] },
    ],
    faqs: [{ q: "Is an 11-month inspection the same as a DLP inspection?", a: "It is a DLP inspection timed specifically at the end of the period. A DLP inspection can be done at any point during the period when a problem appears." }],
    related: ["dlpInspection", "reInspection", "moistureDetection", "hvacMep"],
  },
  reInspection: {
    metaTitle: "Property Re-Inspection | Verify Snag Fixes (De-Snagging)",
    metaDescription: "Property re-inspection (de-snagging): we check that every defect in your snagging report was fixed properly by the developer before you sign off.",
    breadcrumb: "Property re-inspection",
    navLabel: "Re-inspection",
    summary: "Confirm the developer actually fixed every reported snag.",
    h1: "Property re-inspection (de-snagging)",
    intro: "Developers often report snags as 'closed' when the fix is partial or has created a new defect. A re-inspection goes through the original report item by item and confirms what has really been fixed.",
    schema: "service",
    includes: ["Item-by-item check against the original report", "Fixed / partly fixed / not fixed status for each snag", "New defects caused by repair work", "Updated report for the developer"],
    sections: [
      { title: "When to book", paragraphs: ["Once the developer confirms repairs are complete, and before your final sign-off or the end of the DLP."] },
      { title: "Typical findings", bullets: ["Paint touch-ups that don't match", "Tiles replaced but grout left uneven", "Silicone redone but gaps remaining", "AC serviced but still not cooling"] },
    ],
    faqs: [{ q: "Can you re-inspect a property snagged by another company?", a: "Yes. Send us the original report and we will verify each item." }],
    related: ["handoverInspection", "elevenMonth", "dlpInspection", "snaggingServices"],
  },
  prePurchase: {
    metaTitle: "Pre-Purchase Property Inspection Dubai | Before You Buy",
    metaDescription: "Pre-purchase property inspection in Dubai: know the real condition of a home before signing the MOU. Use our report to negotiate or budget for repairs.",
    breadcrumb: "Pre-purchase inspection",
    navLabel: "Pre-purchase inspection",
    summary: "Know what you are buying before you sign the MOU.",
    h1: "Pre-purchase property inspection",
    intro: "A fresh coat of paint can hide a lot. A pre-purchase inspection tells you the real condition of a home before you commit, so you can negotiate the price, ask the seller to fix issues or walk away.",
    schema: "service",
    includes: ["Signs of past or active leaks", "Cracks and structural concerns", "Age and performance of AC units", "Electrical safety and DB panel condition", "Water heater, pumps and plumbing", "Wear on kitchens, bathrooms and joinery"],
    sections: [
      { title: "Use the report to negotiate", paragraphs: ["Each finding includes a severity rating, so you can separate deal-breakers from cosmetic items and discuss repair costs with the seller."] },
      { title: "Timing", paragraphs: ["Book after your offer is accepted and before the MOU or Form F is signed. We can usually inspect within a few days."] },
    ],
    faqs: [{ q: "Can you inspect an occupied property?", a: "Yes. We work around tenants or owners and need access to all rooms, the AC units and the DB panel." }],
    related: ["secondaryInspection", "propertyInspection", "thermalImaging", "moistureDetection"],
  },
  secondaryInspection: {
    metaTitle: "Secondary Property Inspection | Resale & Lived-In Homes",
    metaDescription: "Secondary property inspection for resale and lived-in homes in the UAE: maintenance condition, hidden leaks, AC and electrical health for owners, landlords and tenants.",
    breadcrumb: "Secondary property inspection",
    navLabel: "Secondary inspection",
    summary: "Condition checks for resale, rented and older homes.",
    h1: "Secondary property inspection",
    intro: "Secondary-market homes have a history. This inspection looks at how a property has aged — maintenance, wear, past repairs and hidden problems — for owners, landlords and tenants as well as buyers.",
    schema: "service",
    includes: ["Maintenance condition of AC, plumbing and electrics", "Quality of previous repairs and renovations", "Hidden moisture and mould risk", "Move-in or move-out condition record with photos", "Prioritised maintenance list"],
    sections: [
      { title: "Who it's for", bullets: ["Landlords preparing a unit for new tenants", "Tenants recording condition at move-in or move-out", "Owners planning a renovation", "Buyers of older properties"] },
      { title: "Protect your deposit", paragraphs: ["A dated, photo-documented condition report at move-in helps tenants avoid disputes over damage that was already there."] },
    ],
    faqs: [{ q: "How is this different from a pre-purchase inspection?", a: "A pre-purchase inspection supports a buying decision. A secondary inspection is broader: it also serves owners, landlords and tenants who need a condition record or maintenance plan." }],
    related: ["prePurchase", "propertyInspection", "hvacMep", "moistureDetection"],
  },
  thermalImaging: {
    metaTitle: "Thermal Imaging Inspection Dubai | Find Hidden Leaks & Faults",
    metaDescription: "Thermal imaging inspection in the UAE: detect hidden moisture, AC leaks, missing insulation and electrical hotspots without breaking walls.",
    breadcrumb: "Thermal imaging inspection",
    navLabel: "Thermal imaging",
    summary: "See temperature differences that point to leaks and faults.",
    h1: "Thermal imaging inspection",
    intro: "A thermal camera shows surface temperature differences. In a home, those differences often point to problems you can't see: moisture behind tiles, air leaks around windows, AC duct issues or overheating electrical connections.",
    schema: "service",
    includes: ["Moisture patterns in walls, ceilings and floors", "AC duct and diffuser leaks", "Gaps in insulation around windows and doors", "Hot spots in DB panels and sockets", "Roof and terrace water ingress"],
    sections: [
      { title: "What thermal imaging can and can't do", paragraphs: ["It does not see through walls — it reads surface temperature. We confirm suspected moisture with a moisture meter before reporting it, so findings are reliable."] },
      { title: "Included in our snagging", paragraphs: ["Thermal imaging is part of our standard inspections, and can also be booked on its own to investigate a specific problem."] },
    ],
    faqs: [{ q: "Do you need to open walls?", a: "No. Thermal imaging is non-destructive. If a concealed problem is likely, we recommend where further investigation should happen." }],
    related: ["moistureDetection", "hvacMep", "dlpInspection", "villaSnagging"],
  },
  moistureDetection: {
    metaTitle: "Moisture Detection Inspection | Leak & Damp Investigation UAE",
    metaDescription: "Moisture detection inspection: find damp, hidden leaks and waterproofing failures in bathrooms, kitchens, balconies and roofs using meters and thermal imaging.",
    breadcrumb: "Moisture detection inspection",
    navLabel: "Moisture detection",
    summary: "Track down damp, hidden leaks and waterproofing failures.",
    h1: "Moisture detection inspection",
    intro: "Water damage starts small: a stain on a ceiling, a swollen skirting board, a musty smell. A moisture detection inspection measures where the water is and helps trace where it's coming from.",
    schema: "service",
    includes: ["Moisture meter readings in walls and floors", "Thermal imaging to map damp areas", "Bathroom and kitchen waterproofing indicators", "Balcony, terrace and roof checks", "Plumbing and AC drain leak checks", "Likely source and next-step recommendation"],
    sections: [
      { title: "Common causes we find", bullets: ["Failed shower or bath waterproofing", "Leaking AC condensate drains", "Poor falls on balconies and terraces", "Cracked grout and missing silicone", "Leaking concealed pipes"] },
      { title: "Before it becomes mould", paragraphs: ["Persistent damp can lead to mould and damaged finishes. Early detection usually means a simpler, cheaper repair."] },
    ],
    faqs: [{ q: "Will you find the exact leaking pipe?", a: "We identify the affected area and the most likely source. Confirming a concealed pipe leak may require a plumber to open a small section." }],
    related: ["thermalImaging", "dlpInspection", "townhouseSnagging", "secondaryInspection"],
  },
  hvacMep: {
    metaTitle: "HVAC & MEP Inspection | AC, Electrical & Plumbing Checks UAE",
    metaDescription: "HVAC and MEP inspection in the UAE: AC cooling performance, airflow, FCU and condenser checks plus electrical and plumbing systems, with a detailed report.",
    breadcrumb: "HVAC / MEP inspection",
    navLabel: "HVAC / MEP inspection",
    summary: "AC, electrical and plumbing systems tested in detail.",
    h1: "HVAC and MEP inspection",
    intro: "In the UAE, the AC is the system you rely on most. Our HVAC and MEP inspection tests cooling, airflow, drainage and controls, along with the electrical and plumbing systems behind your walls.",
    schema: "service",
    includes: ["Supply air temperature and cooling performance", "Airflow at each diffuser", "Thermostats and controls", "FCU condition, filters and condensate drainage", "Condenser / outdoor unit condition", "DB panel, RCD/earth leakage, sockets and lighting", "Water pressure, heaters, pumps and drainage"],
    sections: [
      { title: "Signs you need an HVAC check", bullets: ["Rooms that never reach the set temperature", "Water dripping from diffusers or ceilings", "Noisy or vibrating units", "High electricity bills"] },
      { title: "For new and existing homes", paragraphs: ["We include MEP checks in every snagging inspection, and offer this focused inspection for owners and tenants with specific concerns."] },
    ],
    faqs: [{ q: "Do you service or repair the AC?", a: "No. We are independent inspectors: we test and report, so our findings aren't influenced by repair work." }],
    related: ["thermalImaging", "moistureDetection", "dlpInspection", "propertyInspection"],
  },
};

export type { ServiceKey };
